stages:
- stage: build
  displayName: Build Project
  jobs:
  - job: dotnetbuild
    displayName: .NET Build
    pool:
      vmImage: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
    - script: dotnet --version
      displayName: Check .NET Version
    - script: dotnet publish --configuration Release --output out/win --self-contained --runtime win-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
      displayName: Publish Windows application
    - script: dotnet publish --configuration Release --output out/linux --self-contained --runtime linux-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
      displayName: Publish Linux application
    - script: dotnet publish --configuration Release --output out/macos --self-contained --runtime osx-x64 /p:PublishSingleFile=true /p:IncludeSymbolsInSingleFile=true
      displayName: Publish MacOS application
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: out
        artifactName: distributions